[project]
name = "ml-music-classifier"
version = "0.1.0"
description = "Music Genre Classification System"
requires-python = ">=3.12"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    { name = "Anton Kachur" },
    { name = "Dorsa Abbasi" },
    { name = "Kirill Sergienko" },
    { name = "Lada Zhilkina" },
    { name = "Matin Dastanboo" }
]

dependencies = [
    "pydantic-settings>=2.6.1",
    "numpy>=2.1.0",
	"pandas==3.0.2"
]

[dependency-groups]
backend = [
    "fastapi==0.111.0",
    "uvicorn[standard]==0.30.1",
    "pydantic==2.12.5",
    "pydantic-extra-types==2.11.1",
    "pydantic-core==2.41.5",
    "torch==2.9.1",
	"torchaudio==2.9.1",
    "aio-pika>=9.0.0",
    "redis>=5.0.0",
]

ml = [
    "transformers==5.6.2",
    "torch==2.9.1",
	"torchaudio==2.9.1",
    "librosa==0.11.0",
    "soundfile==0.13.1",
	"matplotlib==3.10.9"
]

frontend = [
    "streamlit==1.56.0",
    "requests==2.33.1",
    "Pillow==12.2.0",
    "mutagen==1.47.0",
]

dev = [
    "pytest==8.3.4",
    "flake8==7.1.1",
    "black",
    "isort",
    "pre-commit",
	"optuna==4.8.0",
	"optuna-dashboard==0.20.0",
	"ipywidgets==8.1.8",
]

[tool.pytest.ini_options]
testpaths = ["backend/tests", "ml/tests", "frontend/tests"]
addopts = "-ra --tb=short"
asyncio_mode = "auto"

[tool.flake8]
max-line-length = 100
ignore = ["E203", "W503"]

[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 100

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "torchaudio"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
torchaudio = { index = "torchaudio" }